### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by troglobit** [xu-wang11/FtpServer#1]
Hi,

I'm considering forking your code for FtpServer for use as a very small ftpd that I can use on my laptop.

What type of license are you releasing the software under, or do you consider it to be in the public domain?

**Comment by troglobit** [comment]
... so, I forked. As you can see in the issue history (above), I took the liberty of using the [ISC license](http://en.wikipedia.org/wiki/ISC_license) on the derived work.

I'm also attributing copyright to you, using the email address you've given here on GitHub.

I hope you don't mind, but if you do please let me know!

Best regards
 /Joachim

**Comment by xu-wang11** [comment]
Thanks for your reminding. I have to say I have no idea about licence, I will push a license as soon as possible.

**Comment by troglobit** [comment]
Fixed in commit 8d19c70
